[package]
name = "xtask"
version = "0.1.0"
authors = ["Apollo Developers <opensource@apollographql.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
anyhow = "1"
camino = "1.0"
regex = "1"
which = "4.0.2"

rover = { path = "../../", default-features = false }