name: Tests

on: 
  push:
    branches:
      - "**"
    # Tests are run in the release job on tag pushes -
    # We don't need to run them twice.
    tags-ignore: 
      - "v*"

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ contains(matrix.build, 'nightly') }}
    strategy:
      fail-fast: false
      matrix:
        build: 
          [
            linux-musl-stable,
            linux-gnu-stable,
          ]
        include:
          - build: linux-musl-stable
            os: ubuntu-16.04
            rust: stable
            target: x86_64-unknown-linux-musl
            
          - build: linux-gnu-stable
            os: ubuntu-16.04
            rust: stable
            target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.build }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.build }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ matrix.build }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.build }}-cargo-index-
            
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
          rustup target add ${{ matrix.target }}

      - name: Install musl-tools
        if: startsWith(matrix.build, 'linux-musl-')
        run: |
          sudo apt update
          sudo apt install musl-tools
                
      - name: Run Tests
        run: cargo xtask test --verbose --target ${{ matrix.target }}

      - name: Upload schema.graphql
        if: ${{ matrix.build == 'linux-gnu-stable' }}
        uses: actions/upload-artifact@v2
        with:
          name: schema.graphql
          path: ./crates/rover-client/.schema/schema.graphql

  second_test: 
    name: Second Test
    runs-on: ubuntu-16.04
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Rename schema.graphql
        shell: bash
        run: mv ./linux-gnu-stable/schema.graphql ./rover-v0.10.0-schema.graphql

      - name: Read contents of schema.graphql
        shell: bash
        run: cat ./rover-v0.10.0-schema.graphql